### ISSUE TITLE
disallow using an async function as a Promise executor (no-async-promise-executor)

### ISSUE THREAD

**Issue by tghelere** [arthurzeras/series-wished#1]
https://github.com/arthurzeras/series-wished/blob/0da0ffc5d047f20f7db7150890fc74d9e023d4f5/src/modules/auth/store/actions.js#L27

E aii Arthur, tudo bem?
A partir da versão 5.3.0. do ESLint, não é mais permitido o uso de uma função assíncrona como executor do Promise. Porém não estou sabendo como corrigir este erro. 

Qual você acha que seria a melhor forma?
Apaguei ao async / await, e o erro desapareceu, porém obtive outros erros.
Cheguei pensar em fazer downgrade do ESLint por ter um pouco de pressa no meu projeto e ter travado nessa parte.

Obrigado pelo ótimo conteúdo

**Comment by t00lmaker** [comment]
Ola, 

acredito que nao precisa ser necessariamente uma promisse, particulamente eu resolvi da seguinte forma: 

```javascript
export const ActionLoadSession = ({ dispatch }) => {
  (async function () {  
    try{
      const { data : { app, user } } = await services.auth.session()
      dispatch('ActionSetUser', user)
      dispatch('ActionSetApp', app)
    }catch (err) {
      dispatch('ActionSignOut')
    }
  })()
}
```

**Comment by tghelere** [comment]
E aii Luan, blz?
Acabei resolvendo da seguinte forma

```js
export const ActionLoadSession = async ({ dispatch }) => {
  try {
    const { data: { user } } = await services.auth.loadSession()
    dispatch('ActionSetUser', user)
  } catch (error) {
    dispatch('ActionLogout')
    return Promise.reject(error)
  }
}
```
